version: '3'
services:
        web:
                image: cskinp_port_v1
                build: .
                ports:
                        - "8223:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
